name: FingerprintJSPro

options:
  deploymentTarget:
    iOS: 10.0

settings:
  MARKETING_VERSION: 1.1.0
  CURRENT_PROJECT_VERSION: 2
  TARGETED_DEVICE_FAMILY: 1,2
  PRODUCT_BUNDLE_IDENTIFIER: com.fingerprintjspro.$(TARGET_NAME)
  CODE_SIGN_STYLE: Automatic

packages:
  FingerprintJSPro:
    path: ./

targets:
  FingerprintJSPro:
    platform: iOS
    type: framework
    sources: Sources/FingerprintJSPro
    info:
      path: Sources/FingerprintJSPro/Resources/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
  Demo:
    platform: iOS
    type: application
    sources: Sources/Demo
    info:
      path: Sources/Demo/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    dependencies:
      - package: FingerprintJSPro
  DemoJavaScript:
    platform: iOS
    deploymentTarget: 14.0
    type: application
    sources: Sources/DemoJavaScript
    settings:
    info:
      path: Sources/DemoJavaScript/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true

