name: Example

options:
  deploymentTarget:
    iOS: 10.0

settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  TARGETED_DEVICE_FAMILY: 1,2
  PRODUCT_BUNDLE_IDENTIFIER: com.fingerprintjspro.example
packages:
  FingerprintJSPro:
    path: ./

targets:
  FingerprintJSPro_Example:
    platform: iOS
    type: application
    info:
      path: Sources/Example/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
    sources: Sources/Example
    dependencies:
     - package: FingerprintJSPro
